use std::fs;

fn main() {
    // ── 1. Conditional command list ──
    #[allow(unused_mut)]
    let mut commands: Vec<&str> = vec![
        "is_available",
        "request_permissions",
        "check_permissions",
        "open_settings",
    ];

    #[cfg(feature = "activity")]
    commands.push("query_aggregated");
    #[cfg(feature = "sleep")]
    commands.push("query_sleep");
    #[cfg(feature = "workouts")]
    commands.push("query_workouts");
    #[cfg(feature = "heart-rate")]
    commands.push("query_heart_rate_samples");

    // ── 2. Generate permissions/default.toml ──
    #[allow(unused_mut)]
    let mut perms = vec![
        "allow-is-available",
        "allow-request-permissions",
        "allow-check-permissions",
        "allow-open-settings",
    ];

    #[cfg(feature = "activity")]
    perms.push("allow-query-aggregated");
    #[cfg(feature = "sleep")]
    perms.push("allow-query-sleep");
    #[cfg(feature = "workouts")]
    perms.push("allow-query-workouts");
    #[cfg(feature = "heart-rate")]
    perms.push("allow-query-heart-rate-samples");

    let perms_toml = format!(
        r#""$schema" = "schemas/schema.json"

[default]
description = """
Default permissions for the health plugin (auto-generated by build.rs based \
on enabled Cargo features).
"""
permissions = [
{}
]
"#,
        perms.iter()
            .map(|p| format!("  \"{p}\","))
            .collect::<Vec<_>>()
            .join("\n")
    );
    fs::write("permissions/default.toml", perms_toml)
        .expect("failed to write permissions/default.toml");

    // ── 3. Generate AndroidManifest.xml ──
    #[allow(unused_mut)]
    let mut android_perms: Vec<&str> = Vec::new();

    #[cfg(feature = "activity")]
    android_perms.extend_from_slice(&[
        "android.permission.health.READ_STEPS",
        "android.permission.health.READ_DISTANCE",
        "android.permission.health.READ_ACTIVE_CALORIES_BURNED",
        "android.permission.health.READ_TOTAL_CALORIES_BURNED",
    ]);
    #[cfg(feature = "heart-rate")]
    android_perms.extend_from_slice(&[
        "android.permission.health.READ_HEART_RATE",
        "android.permission.health.READ_RESTING_HEART_RATE",
        "android.permission.health.READ_HEART_RATE_VARIABILITY",
    ]);
    #[cfg(feature = "workouts")]
    android_perms.push("android.permission.health.READ_EXERCISE");
    #[cfg(feature = "sleep")]
    android_perms.push("android.permission.health.READ_SLEEP");

    let perm_lines: String = android_perms.iter()
        .map(|p| format!("    <uses-permission android:name=\"{p}\" />"))
        .collect::<Vec<_>>()
        .join("\n");

    let manifest = format!(r#"<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <!-- Auto-generated by build.rs based on enabled Cargo features. -->
{perm_lines}

    <queries>
        <package android:name="com.google.android.apps.healthdata" />
    </queries>

    <application>
        <activity
            android:name="app.tauri.health.PermissionsRationaleActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="androidx.health.ACTION_SHOW_PERMISSIONS_RATIONALE" />
            </intent-filter>
        </activity>

        <activity-alias
            android:name="app.tauri.health.ViewPermissionUsageActivity"
            android:targetActivity="app.tauri.health.PermissionsRationaleActivity"
            android:exported="true"
            android:permission="android.permission.START_VIEW_PERMISSION_USAGE">
            <intent-filter>
                <action android:name="android.intent.action.VIEW_PERMISSION_USAGE" />
                <category android:name="android.intent.category.HEALTH_PERMISSIONS" />
            </intent-filter>
        </activity-alias>
    </application>
</manifest>
"#);
    fs::write("android/src/main/AndroidManifest.xml", manifest)
        .expect("failed to write AndroidManifest.xml");

    // ── 4. Run Tauri plugin builder ──
    tauri_plugin::Builder::new(&commands)
        .android_path("android")
        .ios_path("ios")
        .build();
}
