/*
 Generated by typeshare 1.13.4
 */

import Foundation

/// Unit of an aggregated value.
public enum HealthUnit: String, Codable {
	case count
	/// Meters.
	case m
	case kcal
	case bpm
	/// Milliseconds (HRV).
	case ms
}

public struct AggregatedBucket: Codable {
	/// Epoch ms, device-local bucket bounds.
	public let start: Int64
	public let end: Int64
	/// steps: count; distance: meters; calories: kcal; heartRate /
	/// restingHeartRate: avg bpm; heartRateVariability: avg ms (SDNN on
	/// iOS, RMSSD on Android — baseline-relative comparisons only).
	public let value: Double
	public let unit: HealthUnit
	/// Heart metrics only (heartRate / restingHeartRate /
	/// heartRateVariability).
	public let min: Double?
	public let max: Double?

	public init(start: Int64, end: Int64, value: Double, unit: HealthUnit, min: Double?, max: Double?) {
		self.start = start
		self.end = end
		self.value = value
		self.unit = unit
		self.min = min
		self.max = max
	}
}

public enum HealthPlatform: String, Codable {
	case ios
	case android
	case unsupported
}

/// Why health data is unavailable on this device.
public enum AvailabilityReason: String, Codable {
	/// Android: the Health Connect app needs an update — offer `openSettings`.
	case providerUpdateRequired
	/// Android: the device has no Health Connect provider.
	case providerUnavailable
	/// iOS: HealthKit reports no health data (e.g. old iPads).
	case healthDataUnavailable
	/// Desktop: health data is only available on iOS and Android.
	case unsupportedPlatform
}

public struct Availability: Codable {
	public let available: Bool
	public let platform: HealthPlatform
	/// Present when `available` is false.
	public let reason: AvailabilityReason?

	public init(available: Bool, platform: HealthPlatform, reason: AvailabilityReason?) {
		self.available = available
		self.platform = platform
		self.reason = reason
	}
}

public struct HeartRateSample: Codable {
	public let timestamp: Int64
	public let bpm: Double
	/// Recording app/device name (iOS) or package (Android).
	public let source: String?

	public init(timestamp: Int64, bpm: Double, source: String?) {
		self.timestamp = timestamp
		self.bpm = bpm
		self.source = source
	}
}

/// A readable health metric.
/// 
/// `heartRateVariability` is method-specific per platform — SDNN on iOS,
/// RMSSD on Android (both in ms). The two are NOT comparable; only compare
/// HRV against the same user's own baseline on the same device.
public enum Metric: String, Codable, CaseIterable {
	case steps
	case distance
	case activeCalories
	case totalCalories
	case heartRate
	case restingHeartRate
	case heartRateVariability
	case workouts
	case sleep
}

/// Whether `granted` reflects real per-metric grants.
public enum PermissionAccuracy: String, Codable {
	/// Android: the actual granted set from Health Connect.
	case exact
	/// iOS: HealthKit hides read grants by design; `granted` echoes the
	/// requested metrics and denied ones silently return empty data. Treat
	/// "no data" as possibly-denied and surface `openSettings`.
	case unknown
}

public struct PermissionsResponse: Codable {
	public let granted: [Metric]
	public let state: PermissionAccuracy

	public init(granted: [Metric], state: PermissionAccuracy) {
		self.granted = granted
		self.state = state
	}
}

/// Bucket size for aggregated queries (device-local calendar alignment).
public enum Bucket: String, Codable {
	case day
	case hour
}

public struct QueryAggregatedOptions: Codable {
	/// Must be an aggregatable metric (not `workouts` / `sleep`).
	public let metric: Metric
	/// Epoch milliseconds, inclusive start.
	public let start: Int64
	/// Epoch milliseconds, exclusive end.
	public let end: Int64
	public let bucket: Bucket

	public init(metric: Metric, start: Int64, end: Int64, bucket: Bucket) {
		self.metric = metric
		self.start = start
		self.end = end
		self.bucket = bucket
	}
}

public struct QueryAggregatedResponse: Codable {
	public let buckets: [AggregatedBucket]

	public init(buckets: [AggregatedBucket]) {
		self.buckets = buckets
	}
}

public struct QueryHeartRateSamplesOptions: Codable {
	/// Epoch milliseconds, inclusive start.
	public let start: Int64
	/// Epoch milliseconds, exclusive end.
	public let end: Int64
	/// Max samples returned (most recent kept). Default 1000.
	public let limit: Int64?

	public init(start: Int64, end: Int64, limit: Int64?) {
		self.start = start
		self.end = end
		self.limit = limit
	}
}

public struct QueryHeartRateSamplesResponse: Codable {
	public let samples: [HeartRateSample]

	public init(samples: [HeartRateSample]) {
		self.samples = samples
	}
}

public struct QueryRangeOptions: Codable {
	/// Epoch milliseconds, inclusive start.
	public let start: Int64
	/// Epoch milliseconds, exclusive end.
	public let end: Int64

	public init(start: Int64, end: Int64) {
		self.start = start
		self.end = end
	}
}

public enum SleepStage: String, Codable {
	case awake
	case light
	case deep
	case rem
	case inBed
	/// Platform reported sleep without a stage.
	case asleep
	case outOfBed
	case unknown
}

public struct SleepStageSample: Codable {
	public let stage: SleepStage
	public let start: Int64
	public let end: Int64

	public init(stage: SleepStage, start: Int64, end: Int64) {
		self.stage = stage
		self.start = start
		self.end = end
	}
}

public struct SleepSession: Codable {
	public let start: Int64
	public let end: Int64
	/// Recording app/device name (iOS) or package (Android).
	public let source: String?
	public let stages: [SleepStageSample]

	public init(start: Int64, end: Int64, source: String?, stages: [SleepStageSample]) {
		self.start = start
		self.end = end
		self.source = source
		self.stages = stages
	}
}

public struct QuerySleepResponse: Codable {
	public let sessions: [SleepSession]

	public init(sessions: [SleepSession]) {
		self.sessions = sessions
	}
}

/// Cross-platform workout activity name. Platform exercise types without a
/// common mapping report `other`; the platform-native value is always
/// available in `Workout::raw_activity_type`.
public enum ActivityType: String, Codable {
	case running
	case walking
	case cycling
	case swimming
	case strength
	case hiit
	case yoga
	case hiking
	case elliptical
	case rowing
	case tennis
	case basketball
	case soccer
	case dance
	case pilates
	case stairs
	case golf
	case core
	/// iOS only — HealthKit `.crossTraining` has no Health Connect analog.
	case crossTraining
	case other
}

public struct Workout: Codable {
	public let start: Int64
	public let end: Int64
	public let activityType: ActivityType
	/// Platform-native enum value (HKWorkoutActivityType rawValue on iOS,
	/// ExerciseSessionRecord.EXERCISE_TYPE_* on Android), for exact-type
	/// needs.
	public let rawActivityType: Int64
	public let durationSec: Double
	/// kcal
	public let calories: Double?
	public let distanceMeters: Double?
	/// Recording app/device name (iOS) or package (Android).
	public let source: String?

	public init(start: Int64, end: Int64, activityType: ActivityType, rawActivityType: Int64, durationSec: Double, calories: Double?, distanceMeters: Double?, source: String?) {
		self.start = start
		self.end = end
		self.activityType = activityType
		self.rawActivityType = rawActivityType
		self.durationSec = durationSec
		self.calories = calories
		self.distanceMeters = distanceMeters
		self.source = source
	}
}

public struct QueryWorkoutsResponse: Codable {
	public let workouts: [Workout]

	public init(workouts: [Workout]) {
		self.workouts = workouts
	}
}

public struct RequestPermissionsOptions: Codable {
	public let read: [Metric]

	public init(read: [Metric]) {
		self.read = read
	}
}
