/*
 Generated by typeshare 1.13.4
*/

/** Unit of an aggregated value. */
export enum HealthUnit {
	Count = "count",
	/** Meters. */
	M = "m",
	Kcal = "kcal",
	Bpm = "bpm",
	/** Milliseconds (HRV). */
	Ms = "ms",
}

export interface AggregatedBucket {
	/** Epoch ms, device-local bucket bounds. */
	start: number;
	end: number;
	/**
	 * steps: count; distance: meters; calories: kcal; heartRate /
	 * restingHeartRate: avg bpm; heartRateVariability: avg ms (SDNN on
	 * iOS, RMSSD on Android — baseline-relative comparisons only).
	 */
	value: number;
	unit: HealthUnit;
	/**
	 * Heart metrics only (heartRate / restingHeartRate /
	 * heartRateVariability).
	 */
	min?: number;
	max?: number;
}

export enum HealthPlatform {
	Ios = "ios",
	Android = "android",
	Unsupported = "unsupported",
}

/** Why health data is unavailable on this device. */
export enum AvailabilityReason {
	/** Android: the Health Connect app needs an update — offer `openSettings`. */
	ProviderUpdateRequired = "providerUpdateRequired",
	/** Android: the device has no Health Connect provider. */
	ProviderUnavailable = "providerUnavailable",
	/** iOS: HealthKit reports no health data (e.g. old iPads). */
	HealthDataUnavailable = "healthDataUnavailable",
	/** Desktop: health data is only available on iOS and Android. */
	UnsupportedPlatform = "unsupportedPlatform",
}

export interface Availability {
	available: boolean;
	platform: HealthPlatform;
	/** Present when `available` is false. */
	reason?: AvailabilityReason;
}

export interface HeartRateSample {
	timestamp: number;
	bpm: number;
	/** Recording app/device name (iOS) or package (Android). */
	source?: string;
}

/**
 * A readable health metric.
 * 
 * `heartRateVariability` is method-specific per platform — SDNN on iOS,
 * RMSSD on Android (both in ms). The two are NOT comparable; only compare
 * HRV against the same user's own baseline on the same device.
 */
export enum Metric {
	Steps = "steps",
	Distance = "distance",
	ActiveCalories = "activeCalories",
	TotalCalories = "totalCalories",
	HeartRate = "heartRate",
	RestingHeartRate = "restingHeartRate",
	HeartRateVariability = "heartRateVariability",
	Workouts = "workouts",
	Sleep = "sleep",
}

/** Whether `granted` reflects real per-metric grants. */
export enum PermissionAccuracy {
	/** Android: the actual granted set from Health Connect. */
	Exact = "exact",
	/**
	 * iOS: HealthKit hides read grants by design; `granted` echoes the
	 * requested metrics and denied ones silently return empty data. Treat
	 * "no data" as possibly-denied and surface `openSettings`.
	 */
	Unknown = "unknown",
}

export interface PermissionsResponse {
	granted: Metric[];
	state: PermissionAccuracy;
}

/** Bucket size for aggregated queries (device-local calendar alignment). */
export enum Bucket {
	Day = "day",
	Hour = "hour",
}

export interface QueryAggregatedOptions {
	/** Must be an aggregatable metric (not `workouts` / `sleep`). */
	metric: Metric;
	/** Epoch milliseconds, inclusive start. */
	start: number;
	/** Epoch milliseconds, exclusive end. */
	end: number;
	bucket: Bucket;
}

export interface QueryAggregatedResponse {
	buckets: AggregatedBucket[];
}

export interface QueryHeartRateSamplesOptions {
	/** Epoch milliseconds, inclusive start. */
	start: number;
	/** Epoch milliseconds, exclusive end. */
	end: number;
	/** Max samples returned (most recent kept). Default 1000. */
	limit?: number;
}

export interface QueryHeartRateSamplesResponse {
	samples: HeartRateSample[];
}

export interface QueryRangeOptions {
	/** Epoch milliseconds, inclusive start. */
	start: number;
	/** Epoch milliseconds, exclusive end. */
	end: number;
}

export enum SleepStage {
	Awake = "awake",
	Light = "light",
	Deep = "deep",
	Rem = "rem",
	InBed = "inBed",
	/** Platform reported sleep without a stage. */
	Asleep = "asleep",
	OutOfBed = "outOfBed",
	Unknown = "unknown",
}

export interface SleepStageSample {
	stage: SleepStage;
	start: number;
	end: number;
}

export interface SleepSession {
	start: number;
	end: number;
	/** Recording app/device name (iOS) or package (Android). */
	source?: string;
	stages: SleepStageSample[];
}

export interface QuerySleepResponse {
	sessions: SleepSession[];
}

/**
 * Cross-platform workout activity name. Platform exercise types without a
 * common mapping report `other`; the platform-native value is always
 * available in `Workout::raw_activity_type`.
 */
export enum ActivityType {
	Running = "running",
	Walking = "walking",
	Cycling = "cycling",
	Swimming = "swimming",
	Strength = "strength",
	Hiit = "hiit",
	Yoga = "yoga",
	Hiking = "hiking",
	Elliptical = "elliptical",
	Rowing = "rowing",
	Tennis = "tennis",
	Basketball = "basketball",
	Soccer = "soccer",
	Dance = "dance",
	Pilates = "pilates",
	Stairs = "stairs",
	Golf = "golf",
	Core = "core",
	/** iOS only — HealthKit `.crossTraining` has no Health Connect analog. */
	CrossTraining = "crossTraining",
	Other = "other",
}

export interface Workout {
	start: number;
	end: number;
	activityType: ActivityType;
	/**
	 * Platform-native enum value (HKWorkoutActivityType rawValue on iOS,
	 * ExerciseSessionRecord.EXERCISE_TYPE_* on Android), for exact-type
	 * needs.
	 */
	rawActivityType: number;
	durationSec: number;
	/** kcal */
	calories?: number;
	distanceMeters?: number;
	/** Recording app/device name (iOS) or package (Android). */
	source?: string;
}

export interface QueryWorkoutsResponse {
	workouts: Workout[];
}

export interface RequestPermissionsOptions {
	read: Metric[];
}

