/**
 * Generated by typeshare 1.13.4
 */

package app.tauri.health

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/// Unit of an aggregated value.
@Serializable
enum class HealthUnit(val string: String) {
	@SerialName("count")
	Count("count"),
	/// Meters.
	@SerialName("m")
	M("m"),
	@SerialName("kcal")
	Kcal("kcal"),
	@SerialName("bpm")
	Bpm("bpm"),
	/// Milliseconds (HRV).
	@SerialName("ms")
	Ms("ms"),
}

@Serializable
data class AggregatedBucket (
	/// Epoch ms, device-local bucket bounds.
	val start: Long,
	val end: Long,
	/// steps: count; distance: meters; calories: kcal; heartRate /
	/// restingHeartRate: avg bpm; heartRateVariability: avg ms (SDNN on
	/// iOS, RMSSD on Android — baseline-relative comparisons only).
	val value: Double,
	val unit: HealthUnit,
	/// Heart metrics only (heartRate / restingHeartRate /
	/// heartRateVariability).
	val min: Double? = null,
	val max: Double? = null
)

@Serializable
enum class HealthPlatform(val string: String) {
	@SerialName("ios")
	Ios("ios"),
	@SerialName("android")
	Android("android"),
	@SerialName("unsupported")
	Unsupported("unsupported"),
}

/// Why health data is unavailable on this device.
@Serializable
enum class AvailabilityReason(val string: String) {
	/// Android: the Health Connect app needs an update — offer `openSettings`.
	@SerialName("providerUpdateRequired")
	ProviderUpdateRequired("providerUpdateRequired"),
	/// Android: the device has no Health Connect provider.
	@SerialName("providerUnavailable")
	ProviderUnavailable("providerUnavailable"),
	/// iOS: HealthKit reports no health data (e.g. old iPads).
	@SerialName("healthDataUnavailable")
	HealthDataUnavailable("healthDataUnavailable"),
	/// Desktop: health data is only available on iOS and Android.
	@SerialName("unsupportedPlatform")
	UnsupportedPlatform("unsupportedPlatform"),
}

@Serializable
data class Availability (
	val available: Boolean,
	val platform: HealthPlatform,
	/// Present when `available` is false.
	val reason: AvailabilityReason? = null
)

@Serializable
data class HeartRateSample (
	val timestamp: Long,
	val bpm: Double,
	/// Recording app/device name (iOS) or package (Android).
	val source: String? = null
)

/// A readable health metric.
/// 
/// `heartRateVariability` is method-specific per platform — SDNN on iOS,
/// RMSSD on Android (both in ms). The two are NOT comparable; only compare
/// HRV against the same user's own baseline on the same device.
@Serializable
enum class Metric(val string: String) {
	@SerialName("steps")
	Steps("steps"),
	@SerialName("distance")
	Distance("distance"),
	@SerialName("activeCalories")
	ActiveCalories("activeCalories"),
	@SerialName("totalCalories")
	TotalCalories("totalCalories"),
	@SerialName("heartRate")
	HeartRate("heartRate"),
	@SerialName("restingHeartRate")
	RestingHeartRate("restingHeartRate"),
	@SerialName("heartRateVariability")
	HeartRateVariability("heartRateVariability"),
	@SerialName("workouts")
	Workouts("workouts"),
	@SerialName("sleep")
	Sleep("sleep"),
}

/// Whether `granted` reflects real per-metric grants.
@Serializable
enum class PermissionAccuracy(val string: String) {
	/// Android: the actual granted set from Health Connect.
	@SerialName("exact")
	Exact("exact"),
	/// iOS: HealthKit hides read grants by design; `granted` echoes the
	/// requested metrics and denied ones silently return empty data. Treat
	/// "no data" as possibly-denied and surface `openSettings`.
	@SerialName("unknown")
	Unknown("unknown"),
}

@Serializable
data class PermissionsResponse (
	val granted: List<Metric>,
	val state: PermissionAccuracy
)

/// Bucket size for aggregated queries (device-local calendar alignment).
@Serializable
enum class Bucket(val string: String) {
	@SerialName("day")
	Day("day"),
	@SerialName("hour")
	Hour("hour"),
}

@Serializable
data class QueryAggregatedOptions (
	/// Must be an aggregatable metric (not `workouts` / `sleep`).
	val metric: Metric,
	/// Epoch milliseconds, inclusive start.
	val start: Long,
	/// Epoch milliseconds, exclusive end.
	val end: Long,
	val bucket: Bucket
)

@Serializable
data class QueryAggregatedResponse (
	val buckets: List<AggregatedBucket>
)

@Serializable
data class QueryHeartRateSamplesOptions (
	/// Epoch milliseconds, inclusive start.
	val start: Long,
	/// Epoch milliseconds, exclusive end.
	val end: Long,
	/// Max samples returned (most recent kept). Default 1000.
	val limit: Long? = null
)

@Serializable
data class QueryHeartRateSamplesResponse (
	val samples: List<HeartRateSample>
)

@Serializable
data class QueryRangeOptions (
	/// Epoch milliseconds, inclusive start.
	val start: Long,
	/// Epoch milliseconds, exclusive end.
	val end: Long
)

@Serializable
enum class SleepStage(val string: String) {
	@SerialName("awake")
	Awake("awake"),
	@SerialName("light")
	Light("light"),
	@SerialName("deep")
	Deep("deep"),
	@SerialName("rem")
	Rem("rem"),
	@SerialName("inBed")
	InBed("inBed"),
	/// Platform reported sleep without a stage.
	@SerialName("asleep")
	Asleep("asleep"),
	@SerialName("outOfBed")
	OutOfBed("outOfBed"),
	@SerialName("unknown")
	Unknown("unknown"),
}

@Serializable
data class SleepStageSample (
	val stage: SleepStage,
	val start: Long,
	val end: Long
)

@Serializable
data class SleepSession (
	val start: Long,
	val end: Long,
	/// Recording app/device name (iOS) or package (Android).
	val source: String? = null,
	val stages: List<SleepStageSample>
)

@Serializable
data class QuerySleepResponse (
	val sessions: List<SleepSession>
)

/// Cross-platform workout activity name. Platform exercise types without a
/// common mapping report `other`; the platform-native value is always
/// available in `Workout::raw_activity_type`.
@Serializable
enum class ActivityType(val string: String) {
	@SerialName("running")
	Running("running"),
	@SerialName("walking")
	Walking("walking"),
	@SerialName("cycling")
	Cycling("cycling"),
	@SerialName("swimming")
	Swimming("swimming"),
	@SerialName("strength")
	Strength("strength"),
	@SerialName("hiit")
	Hiit("hiit"),
	@SerialName("yoga")
	Yoga("yoga"),
	@SerialName("hiking")
	Hiking("hiking"),
	@SerialName("elliptical")
	Elliptical("elliptical"),
	@SerialName("rowing")
	Rowing("rowing"),
	@SerialName("tennis")
	Tennis("tennis"),
	@SerialName("basketball")
	Basketball("basketball"),
	@SerialName("soccer")
	Soccer("soccer"),
	@SerialName("dance")
	Dance("dance"),
	@SerialName("pilates")
	Pilates("pilates"),
	@SerialName("stairs")
	Stairs("stairs"),
	@SerialName("golf")
	Golf("golf"),
	@SerialName("core")
	Core("core"),
	/// iOS only — HealthKit `.crossTraining` has no Health Connect analog.
	@SerialName("crossTraining")
	CrossTraining("crossTraining"),
	@SerialName("other")
	Other("other"),
}

@Serializable
data class Workout (
	val start: Long,
	val end: Long,
	val activityType: ActivityType,
	/// Platform-native enum value (HKWorkoutActivityType rawValue on iOS,
	/// ExerciseSessionRecord.EXERCISE_TYPE_* on Android), for exact-type
	/// needs.
	val rawActivityType: Long,
	val durationSec: Double,
	/// kcal
	val calories: Double? = null,
	val distanceMeters: Double? = null,
	/// Recording app/device name (iOS) or package (Android).
	val source: String? = null
)

@Serializable
data class QueryWorkoutsResponse (
	val workouts: List<Workout>
)

@Serializable
data class RequestPermissionsOptions (
	val read: List<Metric>
)

